name: Deploy app to EC2

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
      platform:
        type: string
        required: true
      environment:
        type: string
        required: true
        default: 'None'
      app:
        type: string
        required: true
      app_user:
        type: string
        description: The user on the remote server that owns the application files (e.g., "www-data").
        required: true
      enable_maintenance_mode:
        type: boolean
        required: false
        default: false
      aws_region:
        type: string
        required: true
      aws_role_to_assume:
        type: string
        required: true
      build_tool:
        type: string
        required: true
        default: ''
      build_args:
        description: "Optional build arguments to pass to the build tool (e.g., node_version)."
        type: string
        required: false
        default: "{}"
      target_framework:
        type: string
        required: true
      runtime_commands:
        description: "Optional runtime commands string separated by semicolons to execute on the server for starting app. Applicable to python/django."
        type: string
        required: false
      ignore_vulns:
        description: "If true, vulnerability findings won't fail the workflow."
        type: boolean
        required: false
        default: false
      build:
        description: Run build job
        type: boolean
        required: false
        default: true

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      SSM_PREFIX: ${{ steps.target.outputs.ssm_prefix }}
    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws_region }}

      - name: Output target vars
        id: target
        run: |
          APP_INFO=$(aws ssm get-parameter --with-decryption --name /${{ inputs.project }}/${{ inputs.platform }}/${{ inputs.environment }}/${{ inputs.app }}/info --query 'Parameter.Value' --output text)

          if [ -z "$APP_INFO" ]; then
              echo "ERROR: SSM parameter is empty or could not be fetched"
              exit 1
          fi

          APP_SSM_PREFIX=$(echo $APP_INFO | jq -r '.app_ssm_prefix')

          # TODO: prefix should contain environment and app
          echo "ssm_prefix=/$APP_SSM_PREFIX/${{ inputs.environment }}/${{ inputs.app }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    if: ${{ inputs.build }}
    needs:
      - init
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Checkout reusable ci workflows
        uses: actions/checkout@v4
        with:
          repository: systemax64/ci-workflows
          ref: main
          path: .github/ci-workflows
          ssh-key: ${{ secrets.PIPELINE_WORKFLOWS_SSH_KEY }}
          persist-credentials: false

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws_region }}

      - name: Build .env file
        run: |
          chmod +x ./.github/ci-workflows/.github/workflows/scripts/build-env.sh
          ./.github/ci-workflows/.github/workflows/scripts/build-env.sh ${{ needs.init.outputs.SSM_PREFIX }}

      - name: Build app
        uses: ./.github/ci-workflows/composite/build-ec2
        with:
          build_tool: ${{ inputs.build_tool }}
          build_args: ${{ inputs.build_args }}

      - name: Export a short hash of the .env for use as a cache/version key
        run: |
          echo "ENV_HASH=$(md5sum .env | cut -c 1-5)" >> $GITHUB_ENV

      - name: Create artifact archive
        run: |
          tar \
            --exclude='./.git' \
            --exclude='./.github/ci-workflows/.git' \
            -czf /tmp/${{ inputs.app }}-build.tar.gz .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: /tmp/${{ inputs.app }}-build.tar.gz
          archive: false
          retention-days: 1
          if-no-files-found: error

  oss-security:
    needs:
      - build
    name: security
    uses: ./.github/workflows/security.yml
    with:
      sec_tool: ${{ inputs.build_tool }}
      artifact_name: ${{ inputs.app }}-build.tar.gz
      ignore_vulns: ${{ inputs.ignore_vulns }}

  deploy:
    if: ${{ inputs.environment != 'None' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.platform }}
    needs:
      - init
      - build
      - oss-security
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Install python dependencies
        run: |
          pipx inject ansible-core botocore boto3 

      - name: Checkout reusable ci workflows
        uses: actions/checkout@v4
        with:
          repository: systemax64/ci-workflows
          ref: main
          path: .github/ci-workflows
          ssh-key: ${{ secrets.PIPELINE_WORKFLOWS_SSH_KEY }}
          persist-credentials: false

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.app }}-build.tar.gz
          path: /tmp/artifact

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws_region }}

      - name: Generate inventory
        working-directory: ./.github/ci-workflows/ansible
        env:
          PROJECT: ${{ inputs.project }}
          PLATFORM: ${{ inputs.platform }}
          ENVIRONMENT: ${{ inputs.environment }}
          APP_NAME: ${{ inputs.app }}
          AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
        run: |
          chmod +x ./generate-inventory.sh
          ./generate-inventory.sh

      - name: Run deploy ansible playbook
        working-directory: ./.github/ci-workflows/ansible
        run: |
          ansible-playbook --user admin -i inventories/ \
          -e "artifact=/tmp/artifact/${{ inputs.app }}-build.tar.gz" \
          -e "app=${{ inputs.app }}" \
          -e "app_user=${{ inputs.app_user }}" \
          -e "runtime_commands=${{ inputs.runtime_commands }}" \
          deploy/${{ inputs.target_framework }}.yml
