name: Deploy app to ECS

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
      platform:
        type: string
        required: true
      environment:
        type: string
        required: true
        default: 'None'
      app:
        type: string
        required: true
      enable_maintenance_mode:
        type: boolean
        required: false
        default: false
      ctnr_command:
        type: string
        required: true
      sec_tool:
        type: string
        required: true
      aws_region:
        type: string
        required: true
      aws_role_to_assume:
        type: string
        required: true

jobs:
  init:
    runs-on: ubuntu-latest

    outputs:
      ECS_CLUSTER: ${{ steps.target.outputs.cluster }}
      ECS_SERVICE: ${{ steps.target.outputs.service }}
      ECR_REGISTRY: ${{ steps.target.outputs.ecr_registry }}
      ECR_REPO: ${{ steps.target.outputs.ecr_repo }}
      SSM_PREFIX: ${{ steps.target.outputs.ssm_prefix }}

    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: 'no'

      - name: Set target vars
        id: target
        run: |
          APP_INFO=$(aws ssm get-parameter --with-decryption --name /${{ inputs.project }}/${{ inputs.platform }}/${{ inputs.environment }}/${{ inputs.app }}/info --query 'Parameter.Value' --output text)

          if [ -z "$APP_INFO" ]; then
              echo "ERROR: SSM parameter is empty or could not be fetched"
              exit 1
          fi

          ECS_CLUSTER=$(echo $APP_INFO | jq -r '.ecs_cluster')
          ECS_SERVICE=$(echo $APP_INFO | jq -r '.ecs_service')
          ECR_REPOSITORY_URL=$(echo $APP_INFO | jq -r '.ecr_repository_url')
          ECR_REGISTRY=$(echo $ECR_REPOSITORY_URL | cut -d'/' -f1)
          ECR_REPO=$(echo $ECR_REPOSITORY_URL | cut -d'/' -f2)
          APP_SSM_PREFIX=$(echo $APP_INFO | jq -r '.app_ssm_prefix')

          echo "cluster=$ECS_CLUSTER" >> $GITHUB_OUTPUT
          echo "service=$ECS_SERVICE" >> $GITHUB_OUTPUT
          echo "ecr_registry=$ECR_REGISTRY" >> $GITHUB_OUTPUT
          echo "ecr_repo=$ECR_REPO" >> $GITHUB_OUTPUT
          echo "ssm_prefix=/$APP_SSM_PREFIX/${{ inputs.environment }}/${{ inputs.app }}" >> $GITHUB_OUTPUT

      - name: Print deployment information
        run: |
          echo Deploying to "${{ inputs.environment }}" on platform "${{ inputs.platform }}"

  build:
    runs-on: ubuntu-latest
    needs:
      - init

    permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Checkout reusable ci workflows
        uses: actions/checkout@v4
        with:
          repository: systemax64/ci-workflows
          ref: main
          path: .github/ci-workflows
          ssh-key: ${{ secrets.PIPELINE_WORKFLOWS_SSH_KEY }}
          persist-credentials: false

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: 'no'

      - name: Build .env file
        id: env
        run: |
          chmod +x ./.github/ci-workflows/.github/workflows/scripts/build-env.sh
          ./.github/ci-workflows/.github/workflows/scripts/build-env.sh ${{ needs.init.outputs.SSM_PREFIX }}

          echo "hash=$(md5sum .env | cut -c 1-5)" >> $GITHUB_OUTPUT

      - name: Build app
        id: build
        uses: ./.github/ci-workflows/composite/build-ecs
        with:
          gh_repo: ${{ github.repository }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          ecr_registry: ${{ needs.init.outputs.ECR_REGISTRY }}
          ecr_registry_username: ${{ vars[format('{0}_AWS_KEY_ID', needs.init.outputs.AWS_CREDS_PREFIX)] }}
          ecr_registry_password: ${{ secrets[format('{0}_AWS_KEY', needs.init.outputs.AWS_CREDS_PREFIX)] }}
          ecr_repo: ${{ needs.init.outputs.ECR_REPO }}
          ssm_prefix: ${{ needs.init.outputs.SSM_PREFIX }}
          ref_name: ${{ github.ref_name }}
          environment: ${{ inputs.environment }}
          secrets_json: ${{ toJson(secrets) }}
          env_hash: ${{ steps.env.outputs.hash }}
    outputs:
      new_image_tag: ${{ steps.build.outputs.new_image_tag }}
      ghcr_image: ${{ steps.build.outputs.ghcr_image }}

  oss-security:
    needs:
      - build
    uses: ./.github/ci-workflows/oss-security.yml
    with:
      sec_tool: ${{ inputs.sec_tool }}
      ghcr_image: ${{ needs.build.outputs.ghcr_image }}

  deploy:
    if: inputs.environment != 'None'
    runs-on: ubuntu-latest
    needs:
      - build
      - init
    concurrency:
      group: deploy-${{ inputs.environment }}

    steps:
      - name: Install boto3
        run: |
          python -m pip install --upgrade boto3

      - name: Checkout reusable ci workflows
        uses: actions/checkout@v4
        with:
          repository: systemax64/ci-workflows
          ref: main
          path: .github/ci-workflows
          ssh-key: ${{ secrets.PIPELINE_WORKFLOWS_SSH_KEY }}
          persist-credentials: false

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: 'no'

      - name: Run deploy action
        uses: ./.github/ci-workflows/composite/deploy
        with:
          ecs_cluster: ${{ needs.init.outputs.ECS_CLUSTER }}
          ecs_service: ${{ needs.init.outputs.ECS_SERVICE }}
          image_uri: "${{ needs.init.outputs.ECR_REGISTRY }}/${{ needs.init.outputs.ECR_REPO }}:${{ needs.build.outputs.new_image_tag }}"
          ctnr_command: ${{ inputs.ctnr_command }}
          enable_maintenance_mode: ${{ inputs.enable_maintenance_mode }}
