name: Deploy app to EC2

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
      platform:
        type: string
        required: true
      environment:
        type: string
        required: true
        default: 'None'
      app:
        type: string
        required: true
      app_user:
        type: string
        description: The user on the remote server that owns the application files (e.g., "www-data").
        required: true
      enable_maintenance_mode:
        type: boolean
        required: false
        default: false
      build_tool:
        type: string
        required: true
        default: ''
      framework:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_region:
        required: true

jobs:
  init:
    if: github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      github.event.action == 'released' ||
      github.event.action == 'published' && github.event.release.prerelease
    runs-on: ubuntu-latest
    environment: ${{ inputs.platform }}
    outputs:
      SSM_PREFIX: ${{ steps.target.outputs.ssm_prefix }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.aws_region }}
          mask-aws-account-id: 'no'

      - name: Set target vars
        id: target
        run: |
          APP_INFO=$(aws ssm get-parameter --with-decryption --name /${{ inputs.project }}/${{ inputs.platform }}/${{ inputs.environment }}/${{ inputs.app }}/info --query 'Parameter.Value' --output text)

          if [ -z "$APP_INFO" ]; then
              echo "ERROR: SSM parameter is empty or could not be fetched"
              exit 1
          fi

          APP_SSM_PREFIX=$(echo $APP_INFO | jq -r '.app_ssm_prefix')

          # TODO: prefix should contain environment and app
          echo "ssm_prefix=/$APP_SSM_PREFIX/${{ inputs.environment }}/${{ inputs.app }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.platform }}
    needs:
      - init
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Checkout reusable pipeline workflows
        uses: actions/checkout@v4
        with:
          repository: systemax64/ci-workflows
          ref: main
          path: .github/ci-workflows
          ssh-key: ${{ secrets.PIPELINE_WORKFLOWS_SSH_KEY }}
          persist-credentials: false

      # TODO: Use secrets:inherit to pass secrets to the reusable workflow instead of setting them here
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.aws_region }}

      - name: Build .env file
        id: env
        uses: ./.github/pipeline-workflows/composite/env
        with:
          ssm_prefix: ${{ needs.init.outputs.SSM_PREFIX }}

      - name: Setup node
        if: ${{ inputs.build_tool == 'npm' }}
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install node modules
        if: ${{ inputs.build_tool == 'npm' }}
        run: npm install
      - name: Build
        if: ${{ inputs.build_tool == 'npm' }}
        run: npm run build

      - name: Create deployment archive
        run: |
          tar \
            --exclude='./.git' \
            --exclude='./.github/pipeline-workflows/.git' \
            -czf /tmp/app-build.tar.gz .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app }}-build
          path: /tmp/app-build.tar.gz
          retention-days: 1
          if-no-files-found: error

  deploy:
    if: ${{ inputs.environment != 'None' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.platform }}
    needs:
      - init
      - build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Install python dependencies
        run: |
          pipx inject ansible-core botocore boto3 

      - name: Checkout reusable pipeline workflows
        uses: actions/checkout@v4
        with:
          repository: systemax64/ci-workflows
          ref: main
          path: .github/ci-workflows
          ssh-key: ${{ secrets.PIPELINE_WORKFLOWS_SSH_KEY }}
          persist-credentials: false

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.app }}-build
          path: /tmp/artifact

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.aws_region }}

      - name: Generate inventory
        working-directory: ./.github/ci-workflows/ansible
        env:
          PROJECT: ${{ inputs.project }}
          PLATFORM: ${{ inputs.platform }}
          ENVIRONMENT: ${{ inputs.environment }}
          APP_NAME: ${{ inputs.app }}
          AWS_DEFAULT_REGION: ${{ secrets.aws_region }}
        run: |
          chmod +x ./generate-inventory.sh
          ./generate-inventory.sh

      - name: Run deploy ansible playbook
        working-directory: ./.github/ci-workflows/ansible
        run: |
          ansible-playbook --user admin -i inventories/ \
          -e "artifact=/tmp/artifact/${{ inputs.app }}-build.tar.gz" \
          -e "app=${{ inputs.app }}" \
          -e "app_user=${{ inputs.app_user }}" \
          deploy/${{ inputs.framework }}.yml
